#!/usr/bin/env python3
"""
Plot Arboria vs sklearn performance from perf CSV.

Creates 4 PNGs:
- classification_fit
- classification_infer
- regression_fit
- regression_infer
Each chart uses two y-axes:
  left: fit/predict time (ms) for sklearn and arboria
  right: ratio (sklearn / arboria)
"""

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Tuple

import matplotlib.pyplot as plt


def load_rows(csv_path: Path = "bench_results_4_tests.csv") -> List[dict]:
    with csv_path.open(newline="") as f:
        return list(csv.DictReader(f))


def to_float(val: str) -> float:
    return float(val) if val not in ("", None) else float("nan")


def collect(
    rows: List[dict],
    task: str,
    metric_key: str,
) -> Tuple[List[int], List[float], List[float], List[float]]:
    # group by n_train
    grouped: Dict[int, Dict[str, float]] = defaultdict(dict)
    for r in rows:
        if r.get("task") != task:
            continue
        n_train = int(r["n_train"])
        lib = r["lib"]
        grouped[n_train][lib] = to_float(r[metric_key])

    xs = sorted(grouped.keys())
    sk = []
    ar = []
    ratio = []
    for n in xs:
        sk_ms = grouped[n].get("sklearn", float("nan"))
        ar_ms = grouped[n].get("arboria", float("nan"))
        sk.append(sk_ms)
        ar.append(ar_ms)
        ratio.append((sk_ms / ar_ms) * 100.0 if ar_ms and ar_ms == ar_ms else float("nan"))
    return xs, sk, ar, ratio


def plot_dual_axis(
    xs: List[int],
    sk: List[float],
    ar: List[float],
    ratio: List[float],
    title: str,
    ylabel_left: str,
    ylabel_right: str,
    out_path: Path,
    *,
    ratio_log: bool = False,
) -> None:
    fig, ax1 = plt.subplots(figsize=(9, 5))

    ax1.plot(xs, sk, marker="o", markersize=2, linewidth=1.0, label="sklearn", color="#4ea1ff")
    ax1.plot(xs, ar, marker="o", markersize=2, linewidth=1.0, label="arboria", color="#66d36a")
    ax1.set_xlabel("n_train")
    ax1.set_xscale("log")
    ax1.set_ylabel(ylabel_left)
    ax1.grid(True, which="major", alpha=0.35, linestyle="--", linewidth=0.6)

    ax2 = ax1.twinx()
    ax2.plot(xs, ratio, marker="s", markersize=2, linewidth=0.9, linestyle="--", label="ratio sk/arb", color="#ffffff")
    ax2.set_ylabel(ylabel_right)
    if ratio_log:
        ax2.set_yscale("log")

    lines, labels = ax1.get_legend_handles_labels()
    lines2, labels2 = ax2.get_legend_handles_labels()
    ax1.legend(lines + lines2, labels + labels2, loc="upper center", bbox_to_anchor=(0.5, 1.02), ncol=3)

    ax1.set_title(title)
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)


def main() -> int:
    parser = argparse.ArgumentParser(description="Plot perf CSV for classification/regression.")
    parser.add_argument("csv", type=Path, help="Path to perf CSV generated by arboria_perf.py")
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path("."),
        help="Output directory for PNGs (default: current directory)",
    )
    args = parser.parse_args()

    rows = load_rows(args.csv)
    args.out_dir.mkdir(parents=True, exist_ok=True)

    plt.style.use("dark_background")
    # Menlo font
    plt.rcParams["font.family"] = "Menlo"

    # Classification
    xs, sk, ar, ratio = collect(rows, "classification", "fit_ms_med")
    plot_dual_axis(
        xs, sk, ar, ratio,
        "Classification - Fit Time",
        "fit time (ms)",
        "sklearn / arboria (%)",
        args.out_dir / "classification_fit.png",
    )

    xs, sk, ar, ratio = collect(rows, "classification", "pred_ms_med")
    plot_dual_axis(
        xs, sk, ar, ratio,
        "Classification - Inference Time",
        "predict time (ms)",
        "sklearn / arboria (%)",
        args.out_dir / "classification_infer.png",
    )

    # Regression
    xs, sk, ar, ratio = collect(rows, "regression", "fit_ms_med")
    plot_dual_axis(
        xs, sk, ar, ratio,
        "Regression - Fit Time",
        "fit time (ms)",
        "sklearn / arboria (%)",
        args.out_dir / "regression_fit.png",
    )

    xs, sk, ar, ratio = collect(rows, "regression", "pred_ms_med")
    plot_dual_axis(
        xs, sk, ar, ratio,
        "Regression - Inference Time",
        "predict time (ms)",
        "sklearn / arboria (%)",
        args.out_dir / "regression_infer.png",
    )

    print(f"Wrote plots to: {args.out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
